/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/CkIsnf9D0Gv
 */
import Link from "next/link";
import {
	NavigationMenuLink,
	NavigationMenuItem,
	NavigationMenuTrigger,
	NavigationMenuContent,
	NavigationMenuList,
	NavigationMenu,
} from "@/components/ui/navigation-menu";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export function Layout() {
	return (
		<div key="1" className="flex flex-col min-h-screen">
			<div className="flex items-center justify-between px-4 py-2 bg-white dark:bg-gray-800 sm:px-6">
				<Link className="flex items-center" href="#">
					<MilkIcon className="h-6 w-6" />
					<span className="sr-only">Acme Inc</span>
				</Link>
				<NavigationMenu className="hidden lg:flex">
					<NavigationMenuList>
						<NavigationMenuItem>
							<NavigationMenuLink className="px-4 py-2" href="#">
								Home
							</NavigationMenuLink>
						</NavigationMenuItem>
						<NavigationMenuItem>
							<NavigationMenuTrigger className="px-4 py-2">
								Services
							</NavigationMenuTrigger>
							<NavigationMenuContent className="w-[200px]">
								<NavigationMenuLink asChild>
									<Link className="block px-4 py-2" href="#">
										Web Development
									</Link>
								</NavigationMenuLink>
								<NavigationMenuLink asChild>
									<Link className="block px-4 py-2" href="#">
										App Development
									</Link>
								</NavigationMenuLink>
							</NavigationMenuContent>
						</NavigationMenuItem>
						<NavigationMenuItem>
							<NavigationMenuLink className="px-4 py-2" href="#">
								About Us
							</NavigationMenuLink>
						</NavigationMenuItem>
						<NavigationMenuItem>
							<NavigationMenuLink className="px-4 py-2" href="#">
								Contact Us
							</NavigationMenuLink>
						</NavigationMenuItem>
					</NavigationMenuList>
				</NavigationMenu>
			</div>
			<main className="flex-1" />
			<footer className="flex flex-col gap-4 py-6 px-4 bg-white dark:bg-gray-800 sm:px-6 lg:flex-row lg:gap-6">
				<div className="flex items-center lg:w-1/4">
					<Link className="flex items-center" href="#">
						<MilkIcon className="h-6 w-6" />
						<span className="sr-only">Acme Inc</span>
					</Link>
				</div>
				<div className="space-y-4 lg:w-1/4">
					<h3 className="text-lg font-bold">Sign up for our newsletter</h3>
					<form className="flex flex-col space-y-2">
						<Input
							className="max-w-md"
							placeholder="Enter your email"
							type="email"
						/>
						<Button>Subscribe</Button>
					</form>
				</div>
				<div className="space-y-4 lg:w-1/4">
					<h3 className="text-lg font-bold">Contact</h3>
					<p>
						<Link className="text-blue-500" href="#">
							info@acme.com
						</Link>
					</p>
				</div>
				<div className="space-y-4 lg:w-1/4">
					<h3 className="text-lg font-bold">Services</h3>
					<p>
						<Link className="text-blue-500" href="#">
							Web Development
						</Link>
					</p>
					<p>
						<Link className="text-blue-500" href="#">
							App Development
						</Link>
					</p>
				</div>
				<div className="space-y-4 lg:w-1/4">
					<h3 className="text-lg font-bold">Our Work</h3>
					<p>
						<Link className="text-blue-500" href="#">
							Project 1
						</Link>
					</p>
					<p>
						<Link className="text-blue-500" href="#">
							Project 2
						</Link>
					</p>
				</div>
				<div className="flex flex-col items-start gap-4 lg:w-1/4">
					<p className="text-lg font-bold">Connect</p>
					<div className="text-blue-500 flex items-start">
						<Link className="flex items-center" href="#">
							<FacebookIcon className="h-6 w-6 text-blue-500" />
							Facebook
						</Link>
					</div>
					<div className="text-blue-500 flex items-start">
						<Link className="flex items-center" href="#">
							<TwitterIcon className="h-6 w-6 text-blue-500" />
							Twitter
						</Link>
					</div>
					<div className="text-blue-500 flex items-start">
						<Link className="flex items-center gap-2" href="#">
							<InstagramIcon className="h-6 w-6 text-blue-500" />
							<span>Instagram</span>
						</Link>
					</div>
				</div>
			</footer>
		</div>
	);
}

function MilkIcon(props) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="M8 2h8" />
			<path d="M9 2v2.789a4 4 0 1-.672 2.219l-.656.984A4 7 10.212V20a2 2 2h6a2 2-2v-9.789a4 0-.672-2.219l-.656-.984A4 1 15 4.788V2" />
			<path d="M7 15a6.472 6.472 0 1 5 6.47" />
		</svg>
	);
}

function FacebookIcon(props) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="M18 2h-3a5 5 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 1-1h3z" />
		</svg>
	);
}

function TwitterIcon(props) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
		</svg>
	);
}

function InstagramIcon(props) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
			<path d="M16 11.37A4 4 0 1 12.63 8 16 11.37z" />
			<line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
		</svg>
	);
}
